### ISSUE TITLE
Can't upgrade puro standalone using "puro upgrade-puro"

### ISSUE THREAD

**Issue by plantiword** [PixelToast/puro#2]
When running "puro upgrade-puro" from a command-line in Windows 10, I get the following message: 
"Upgrading standalone executables is not supported"

**Comment by PixelToast** [comment]
Thanks for taking the time to file an issue!

Which method did you use to install puro? Could you also post the output of `puro --log-level=4 version`

**Comment by plantiword** [comment]
I tried all installers, Desktop Installer, PS command, and standalone. I installed and uninstalled multiple times and only once I got it to work. I uninstalled to reproduce the working case, and it failed again.

This is the output for puro 1.0.0 installer:
[D] Config: PuroConfig(
      gitExecutable: LocalFile: 'git',
      puroRoot: LocalDirectory: 'C:\Users\User\.puro',
      homeDir: LocalDirectory: 'C:\Users\User',
      projectDir: null,
      parentProjectDir: null,
      flutterGitUrl: https://github.com/flutter/flutter.git,
      engineGitUrl: https://github.com/flutter/engine.git,
      releasesJsonUrl: https://storage.googleapis.com/flutter_infra_release/releases/releases_windows.json,
      flutterStorageBaseUrl: https://storage.googleapis.com,
      environmentOverride: null,
    )
[D] > where dart.bat
[D] where finished in 105ms
[V] where: INFORMACIàN: no se pudo encontrar ning£n archivo para los patrones dados.

[V] where subprocess failed with exit code 1
[D] > where flutter.bat
[D] where finished in 105ms
[V] where: INFORMACIàN: no se pudo encontrar ning£n archivo para los patrones dados.

[V] where subprocess failed with exit code 1
[D] PATH: C:\Program Files\WindowsApps\Microsoft.PowerShell_7.3.0.0_x64__8wekyb3d8bbwe;C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin;C:\Program Files\Eclipse Foundation\jdk-8.0.302.8-hotspot\bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files\Python310\Scripts\;C:\Program Files\Python310\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\WireGuard\;C:\ProgramData\chocolatey\bin;D:\tools\TortoiseSVN\bin;d:\tools\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Program Files\PuTTY\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;d:\tools\WinMerge;C:\Users\User\AppData\Local\Microsoft\WindowsApps;C:\Users\User\AppData\Local\GitHubDesktop\bin;C:\Users\User\.dotnet\tools;D:\tools\bazel;d:\tools\nuget;d:\tools\Microsoft VS Code\bin;D:\tools\msys64;D:\tools\CMake\bin;D:\tools\opencv-4.5.5\build\bin\Release;D:\tools\Anaconda3\envs\openCV2;D:\tools\Notepad++;D:\tools\apache-maven-3.8.6\bin;d:\tools\Multipass\bin;C:\Users\User\.puro\bin;C:\Users\User\.puro\shared\pub_cache\bin
[D] puroDartShimFile: C:\Users\User\.puro\bin\dart.bat
[D] puroFlutterShimFile: C:\Users\User\.puro\bin\flutter.bat
[V] Started waiting for lock on C:\Users\User\.puro\prefs.json
[V] Waiting for lock on C:\Users\User\.puro\prefs.json took 0ms
[V] Started waiting for lock on C:\Users\User\.puro\latest_version
[V] Waiting for lock on C:\Users\User\.puro\latest_version took 1ms
[V] Started waiting for lock on C:\Users\User\.puro\prefs.json
[V] Waiting for lock on C:\Users\User\.puro\prefs.json took 0ms
[i] A new version of Puro is available, run `puro upgrade-puro` to upgrade
[i] Puro 1.0.0
    Dart 2.18.3 (stable) (Mon Oct 17 13:23:20 2022 +0000) on "windows_x64"
    "Windows 10 Pro" 10.0 (Build 19044)

And this is using puro .1.13:
[D] FLUTTER_BIN: null
[D] Config: PuroConfig(
      gitExecutable: LocalFile: 'git',
      puroRoot: LocalDirectory: 'C:\Users\User\.puro',
      homeDir: LocalDirectory: 'C:\Users\User',
      projectDir: null,
      parentProjectDir: null,
      flutterGitUrl: https://github.com/flutter/flutter.git,
      engineGitUrl: https://github.com/flutter/engine.git,
      releasesJsonUrl: https://storage.googleapis.com/flutter_infra_release/releases/releases_windows.json,
      flutterStorageBaseUrl: https://storage.googleapis.com,
      environmentOverride: null,
    )
[D] target: PuroBuildTarget.windowsX64
[D] Platform.executable: C:\Users\User\.puro\bin\puro.exe
[D] Platform.resolvedExecutable: D:\tools\.puro\bin\puro.exe
[D] Platform.script: file:///C:/Users/User/.puro/bin/puro.exe
[D] Platform.packageConfig: null
[D] No package root: Platform.packageConfig is null
[D] packageRoot: null
[D] executablePath: d:\tools\.puro\bin\puro.exe
[D] scriptPath: d:\tools\.puro\bin\puro.exe
[D] scriptExtension: .exe
[D] installationType: PuroInstallationType.standalone
[D] version: 1.1.3
[i] Puro 1.1.3 (standalone/windows-x64)
    Dart 2.18.4 (stable) (Tue Nov 1 15:15:07 2022 +0000) on "windows_x64"
PS C:\Windows\System32>

**Comment by plantiword** [comment]
The problem might have been related that c:\users\user\.puro was a symlink to another directory in my PC (not much space left on C drive to hold multiple versions on Flutter). I tried installing to a regular dir using the Desktop Installer for version 1.1.3 and it worked fine this time. Sorry for the confusion.

**Comment by PixelToast** [comment]
The experience can be improved here, I've added symlinked home dir support to the TODOs

**Comment by PixelToast** [comment]
Just published 1.1.4, this should be fixed now, thanks again for reporting the issue!
